# Generated by Django 6.0.2 on 2026-02-08 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('dresscode', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('starts_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64)),
                ('label', models.CharField(max_length=120)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('bool', 'Boolean'), ('enum', 'Enum')], max_length=16)),
                ('required', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=list)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_definitions', to='events.event')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsvp_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=16)),
                ('plus_one_count', models.PositiveSmallIntegerField(default=0)),
                ('allergies', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('dresscode_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('event_id', 'user_id'),
            },
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='events.customfielddefinition')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='events.event')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='events.participation')),
            ],
        ),
        migrations.CreateModel(
            name='ContributionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='events.event')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='events.participation')),
            ],
            options={
                'ordering': ('event_id', 'item_name'),
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['owner'], name='events_even_owner_i_52e16c_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['starts_at'], name='events_even_starts__b01102_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('ends_at__gte', models.F('starts_at')), _connector='OR'), name='event_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='customfielddefinition',
            index=models.Index(fields=['event'], name='events_cust_event_i_dd0428_idx'),
        ),
        migrations.AddConstraint(
            model_name='customfielddefinition',
            constraint=models.UniqueConstraint(fields=('event', 'key'), name='uniq_custom_field_key_per_event'),
        ),
        migrations.AddIndex(
            model_name='participation',
            index=models.Index(fields=['event', 'rsvp_status'], name='events_part_event_i_983412_idx'),
        ),
        migrations.AddIndex(
            model_name='participation',
            index=models.Index(fields=['user'], name='events_part_user_id_310c8b_idx'),
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='uniq_participation_event_user'),
        ),
        migrations.AddIndex(
            model_name='customfieldvalue',
            index=models.Index(fields=['event'], name='events_cust_event_i_a84714_idx'),
        ),
        migrations.AddIndex(
            model_name='customfieldvalue',
            index=models.Index(fields=['event', 'participation'], name='events_cust_event_i_ec1553_idx'),
        ),
        migrations.AddConstraint(
            model_name='customfieldvalue',
            constraint=models.UniqueConstraint(fields=('definition', 'participation'), name='uniq_custom_field_answer_per_participant'),
        ),
        migrations.AddIndex(
            model_name='contributionitem',
            index=models.Index(fields=['event', 'participation'], name='events_cont_event_i_492df8_idx'),
        ),
        migrations.AddConstraint(
            model_name='contributionitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='contribution_positive_quantity'),
        ),
    ]
