# Generated by Django 6.0.2 on 2026-02-18 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_description_comment_document_eventimage_and_more'),
        ('polls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_submissions', to='events.participation')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='polls.poll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['poll', 'user'], name='polls_votes_poll_id_81cee3_idx')],
                'constraints': [models.UniqueConstraint(fields=('poll', 'user'), name='uniq_vote_submission_per_user')],
            },
        ),
    ]
