# Generated by Django 6.0.2 on 2026-02-08 00:59

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitee_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=16)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invitations', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='events.event')),
                ('invitee_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['event', 'status'], name='invitations_event_i_768b87_idx'), models.Index(fields=['expires_at'], name='invitations_expires_319255_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('invitee_user__isnull', False), models.Q(('invitee_email', ''), _negated=True), _connector='OR'), name='invitation_target_present'), models.UniqueConstraint(condition=models.Q(('invitee_user__isnull', False)), fields=('event', 'invitee_user'), name='uniq_invite_user_per_event'), models.UniqueConstraint(django.db.models.functions.text.Lower('invitee_email'), models.F('event'), condition=models.Q(('invitee_email', ''), _negated=True), name='uniq_invite_email_per_event')],
            },
        ),
    ]
